#!/usr/bin/env python3
import argparse
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

parser = argparse.ArgumentParser()
parser.add_argument("--dev", action="store_true", help="Install dev requirements")
parser.add_argument("--tray", action="store_true", help="Install tray client requirements (PyQt5)")
args = parser.parse_args()

# Create virtual environment
builder = venv.EnvBuilder(with_pip=True)
context = builder.ensure_directories(_VENV_DIR)
builder.create(_VENV_DIR)

# Upgrade pip and setuptools
pip = [context.env_exe, "-m", "pip"]
subprocess.check_call(pip + ["install", "--upgrade", "pip", "setuptools", "wheel"])

# Construct install target
install_target = str(_PROGRAM_DIR)
extras = []

if args.dev:
    extras.append("dev")
if args.tray:
    extras.append("tray")

if extras:
    # Example: /path/to/repo[dev,tray]
    install_target += f"[{','.join(extras)}]"

# Install the project and all its dependencies from pyproject.toml
subprocess.check_call(pip + ["install", "-e", install_target])
